### ISSUE TITLE
BIMDataMicrosoftConnector.mez is missing

### ISSUE THREAD

**Issue by yousrakad** [bimdata/BIMDataMicrosoftConnector#1]
BIMDataMicrosoftConnector.mez is missing

**Comment by Amoki** [comment]
Hi,
You can find the mez file here: https://github.com/bimdata/BIMDataMicrosoftConnector/releases/tag/2.1

**Comment by yousrakad** [comment]
Thank you so much !

Le mar. 22 jui. 2021 à 16:25, Hugo Duroux ***@***.***> a
écrit :
